version: '3'
services:
  chatbot:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "8000:8501"
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true

