version: '3'
services:
  chatbot:
    build:
      context: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_ADDRES=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true

